apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
spec:
  containers:
  - name: mysql
    image: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eazy
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: mysql-data
  volumes:
    - name: mysql-pv-storage
      persistentVolumeClaim:
        claimName: pvc
      
